#ifndef _M5STICKC_CONFIG_H_
#define _M5STICKC_CONFIG_H_

#include <driver/gpio.h>

// 红色 LED 和红外发射管
#define M5STICKC_LED_PIN          GPIO_NUM_10
#define M5STICKC_IR_PIN           GPIO_NUM_9

// 按键
#define M5STICKC_BUTTON_A_PIN     GPIO_NUM_37
#define M5STICKC_BUTTON_B_PIN     GPIO_NUM_39

// 彩色 TFT 屏幕
#define M5STICKC_TFT_MOSI_PIN     GPIO_NUM_15
#define M5STICKC_TFT_CLK_PIN      GPIO_NUM_13
#define M5STICKC_TFT_DC_PIN       GPIO_NUM_23
#define M5STICKC_TFT_RST_PIN      GPIO_NUM_18
#define M5STICKC_TFT_CS_PIN       GPIO_NUM_5
#define M5STICKC_TFT_WIDTH        80
#define M5STICKC_TFT_HEIGHT       160

// GROVE 接口
#define M5STICKC_GROVE_SCL_PIN    GPIO_NUM_33
#define M5STICKC_GROVE_SDA_PIN    GPIO_NUM_32

// 麦克风 MIC
#define M5STICKC_MIC_CLK_PIN      GPIO_NUM_0
#define M5STICKC_MIC_DATA_PIN     GPIO_NUM_34

// 六轴 IMU (SH200Q/MPU6886) & 电源管理芯片 (AXP192) & RTC (BM8563)
#define M5STICKC_I2C_SDA_PIN      GPIO_NUM_21
#define M5STICKC_I2C_SCL_PIN      GPIO_NUM_22
#define M5STICKC_AXP192_IRQ_PIN   GPIO_NUM_35
#define M5STICKC_MPU6886_IRQ_PIN  GPIO_NUM_35
#define M5STICKC_BM8563_IRQ_PIN   GPIO_NUM_35

// 电源管理芯片 (AXP192) 充电电流
#define M5STICKC_CHARGE_CURRENT     0.488f
#define M5STICKC_FULL_CHARGE_CURRENT_OFF 0.066f
#define M5STICKC_FULL_CHARGE_CURRENT_ON  0.181f

#endif // _M5STICKC_CONFIG_H_